%  This is for fixing 
% /home/server/project/sierra/EQAR/D99/D04099/MMT/037-063_ibm/037-063.S0
% and outputing as a mat file, with everything in SDM and SDMHD structures
%  run sdm_plot first to load in the *.s0 file

%  fix station coordinates ... omitted/wrong as usual
stcor = [          35.8892   36.7650   35.7615 ; ...1
                   239.5751  238.550  239.4561] ;
TIMEerr = 1
dt = [-1.5867,0,0];
sgn = [ 1,1,-1];

%  for some reason orient is messed up in this file also
orient =  [       270         0;...
         0         0;...
         0         0;...
  270.0000         0;...
         0         0;...
  270.0000         0;...
         0         0;...
         0         0;...
  253.0000         0;...
  349.0000         0;...
   87.0000         0;...
  177.0000         0;...
         0         0;...
   77.6000         0;...
  172.6000         0;...
   82.9000         0;...
  172.9000         0]
orient = orient';

ch_name = chid(1:2,:);
Sdmhd = struct('nbt',nbt,'nt',nt,'nsta',nsta,'nch',nch,'ih',ih,...
   'stcor',stcor,'decl',decl,'chid',chid,'sta',sta,'orient',orient,...
   'ch_name',ch_name)

SDMS = Sdms;
S = Sdms.S;
grouping = 'all';
if(TIMEerr)
  [S] = terrFix(dt,sgn,ih,S,T);
end
[var,sig] = sdm_var(S,grouping,ih,chid);

lambda = zeros(nt,nbt);
U = zeros(nt,nt,nbt)+i*zeros(nt,nt,nbt);

for ib = 1:nbt
   %  solve generalized eigenvalue problem
   [u1,eval1] = eig(S(:,:,ib),diag(var(:,ib)));
   %  scale into eigenvectors of scaled sdm
   u1 = diag(sqrt(var(:,ib)))*u1;
   %  now normalize so that eigenvectors are orthonormal
   normU = sum(conj(u1).*u1,1); normU = 1./sqrt(normU);
   u1 = u1*diag(normU);
   % eigenvectors of scaled sdm ...
   %   u = sqrt(diag(var))*u;
   %  make sure eigenvalues are in correct order ...
   [temp,ind] = sort(diag(eval1));
   ind = ind([nt:-1:1]);
   U(:,:,ib) = u1(:,ind);
   lambda(:,ib) = real(temp([nt:-1:1]));
end

Sdms = struct('T',periods','nf',ndf,'var',var,'S',S,'U',U,...
   'lambda',lambda);
save /home/server/homes/pi/egbert/papers/Sierra/037-063_S0allx.mat  Sdms Sdmhd;
