function [h_check,h_omit] = ch_menu(chid,csta,loc);
global hfig_can_coh_menu
[nchid,nt] = size(chid);
stmonitr
width = width_cc*1.1;

height_1 = height_cc_1;
height = (nt+3)*height_1;
if(nargin < 3)
  loc = loc_cc;
end
rect_fig = [loc width height ];
hfig_can_coh_menu = figure('Position',rect_fig);
for k=1:nt
   rect = [ width*.1 (nt-k)*height_1+5 width*.7 height_1*.8];
   rect_omit = [ width*.8 (nt-k)*height_1+5 width*.1 height_1*.8];

  name = [csta(:,k)' '  ' chid(:,k)' ];
  h_check(k) = uicontrol('style','checkbox', ...
     'parent',hfig_can_coh_menu,...
     'position',rect,...
     'string',name,...
     'value',0,...
     'tag',['C' num2str(k)],...
     'callback','find_ch(h_check,h_omit);');
      
  h_omit(k) = uicontrol('style','checkbox', ...
     'parent',hfig_can_coh_menu,...
     'position',rect_omit,...
     'string','',...
     'value',0,...
     'tag',['O' num2str(k)],...
     'callback','find_ch(h_check,h_omit);');
end  %  loop over channels 1:nt

rect = [ width*.1 (nt+1.6)*height_1+5 width*.8 height_1*.8];
h_plot = uicontrol('style','pushbutton', ...
   'parent',hfig_can_coh_menu,...
   'position',rect,...
   'string','PLOT',...
   'callback','sdm_sub');
        
rect = [ width*.1 (nt+.5)*height_1+5 width*.8 height_1*.8];
h_quit = uicontrol('style','pushbutton','parent',hfig_can_coh_menu,'position', ...
    rect,'string','QUIT','callback','cc_quit');
set(gcf,'Name','Sta./Comp.');
return
